### PR TITLE
Revert "(PDB-4357) replace SHA-1 use with SHA-256"

### PR DESCRIPTION
**Pull request by justinstoller**
This reverts commit 46b4aea42c109079c7201447a4ca6d17c9a7624d.

### CODE REVIEW

**Comment by justinstoller** [comment]
The PR for https://github.com/puppetlabs/jvm-ssl-utils/pull/87 was validated at 952b8248fabadee8fb955f58daa46c9dd8882687 with the http-client PR https://github.com/puppetlabs/clj-http-client/pull/79 at https://github.com/puppetlabs/clj-http-client/pull/79/commits/332834dab290899b16abe3f7ee02ec0c78af4051 with dev builds of Puppet Server and Puppet running Puppet Server's unit & integration tests. For the additional change in 46b4aea I did not re-validate the whole suite of tools together. Unfortunately, when integrating the jvm-ssl-utils 3.0.1 release into Puppet Server (in preparation of releasing clj-parent with it so we can finally finish the clj-http-client PR) there are regressions in Puppet Server's integration tests.

A gist with some debugging is here: [fips integration work](https://gist.github.com/justinstoller/8fa665bf12f445e1de72533397c5b3d6)

Walking through the gist:

This kind of failure is now appearing in our test suite - [example-test-failure.sh](https://gist.github.com/justinstoller/8fa665bf12f445e1de72533397c5b3d6#file-example-test-failure-sh). Which appears to be happening at the ssl validation level. I was able to reproduce using curl ([curl-broken.sh](https://gist.github.com/justinstoller/8fa665bf12f445e1de72533397c5b3d6#file-curl-broken-sh)) and openssl's s_client ([openssl-broken.sh](https://gist.github.com/justinstoller/8fa665bf12f445e1de72533397c5b3d6#file-openssl-broken-sh)). It appears that there's some kind of sslv3 related warnings in there, so I attempted to pass only tlsv1.2 ciphers in, with the same results ([curl w/ explicit cipher](https://gist.github.com/justinstoller/8fa665bf12f445e1de72533397c5b3d6#file-curl-broken-with-explicit-cipher-sh), [openssl w/ explicit cipher](https://gist.github.com/justinstoller/8fa665bf12f445e1de72533397c5b3d6#file-openssl-broken-explicit-cipher-sh)). Running the server without this commit passes tests and gives the expected results from the cli ([curl-working.sh](https://gist.github.com/justinstoller/8fa665bf12f445e1de72533397c5b3d6#file-curl-working-sh), [openssl-working.sh](https://gist.github.com/justinstoller/8fa665bf12f445e1de72533397c5b3d6#file-openssl-working-sh)). Wondering if this was related to OSX's libressl ([this](https://github.com/libressl-portable/portable/issues/443) was one of the few things I could find trying to google the errors) I ran the above testcase on RHEL7 with the same results (host `l8xv6zsb8u0hjop` on the vpn).

I should note that that a) the good and bad certs linked are not the same certs from the earlier debugging out put and b) the testcase should reproducibly fail in Puppet Server with the bad certs as fixtures with in code that doesn't otherwise contain the fips updates, and the testcase should pass with the fips updates but using the good certs (ie, the certs that Puppet Server generates for itself when it starts up using the new jvm-ssl-utils code are the problem).

I'm unclear how the authKeyId and subjectKeyId changes in this commit would be related to sslv3 errors (or if the name in the error is spurious). Nor why this kind of issue wouldn't be caught in clj-http-client's test suite. I'm unfortunately at the end of my debugging knowledge of the topic. Advice much appreciated.

**Comment by justinstoller** [comment]
Hey @robdaemon, I'm having a terrible time with this issue and I was hoping you might be able to shed some light on it? (or maybe know someone who can?)

/cc Puppet Server Team, this is the issue I was talking about yesterday afternoon.

**Comment by robdaemon** [comment]
OpenSSL's tools say SSLv3 generically, so it's not really an SSLv3 issue.

It may be that these parts need to stay SHA1. I wasn't really sure, but erred on the side of caution. I don't mind if this gets reverted.

**Comment by justinstoller** [comment]
Okay. Thanks, @robdaemon !

**Pull request merged**
