### PR TITLE
(maint) Miscellaneous cleanup

### PR DESCRIPTION
**Pull request by mwaggett**
see individual commit messages for details

### CODE REVIEW

**Review by Magisus — APPROVED** [review]

**Comment by Magisus** [comment]
A little curious if there's a downside to the blanket import.

**Comment by mwaggett** [comment]
What kind(s) of downside did you have in mind? Is there something I should investigate?
The only things I could think of were like.. something is a little slower or some package is a little bigger?? ¯\_(ツ)_/¯ no idea

**Comment by Magisus** [comment]
Those things :) Was mostly curious if e.g. Justin had an opinion off the top of his head.

**Comment by mwaggett** [comment]
fwiw, I'm happy to put back the explicit imports if we want, and update my IDE to not do that anymore. but there was already one wildcarded import in there already, so figured there was no explicit decision to not do that.

**Comment by justinstoller** [comment]
Yeah, I don't think the wildcards are a best practice, but I don't think we have strong standards around it (and are already doing it). I'd prefer we didn't make what we're loading any less explicit, but it's not a strong preference (since IDEs don't have much of a problem with it).

**Comment by mwaggett** [comment]
okay, I can put it back! and I can also make the current wildcarded one more explicit.

**Comment by mwaggett** [comment]
okay updated

**Review by Magisus — APPROVED** [review]

**Pull request merged**
