### PR TITLE
(maint) MOAR TESTUTILS

### PR DESCRIPTION
**Pull request by mwaggett**
see individual commit messages for details

### CODE REVIEW

**Comment by Magisus** [comment]
Question about that last commit: why do we reject CRLs that revoke a CA cert? Is that a sign that the whole PKI is void now, and we're going to raise a big error?

**Comment by mwaggett** [comment]
@Magisus yeah - my understanding is that if a new CRL says that one of the intermediate CA certs has been revoked, then we can't trust anything. But I'm not totally sure what the desired workflow is/should be for revoking a CA cert.

**Comment by Magisus** [comment]
That makes sense, though I also don't know what we want to do about it if that happens.

**Review by Magisus — APPROVED** [review]

**Comment by justinstoller** [comment]
IMO, we want to test the workflow of when an intermediate (or ourselves) have been revoked. However, I don't think that failing the update is necessarily the right move. As long as we're getting valid inputs I think we should honor them (iow, we don't want to stand in the way of a customer who is being attacked from bringing down potentially compromised systems).

**Pull request merged**
